language: java

sudo: false

env:
  global:
    - BASEURL=https://archive.apache.org/dist/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.zip
    - FILE=apache-maven-VERSION-bin.zip
    - DIR=apache-maven-VERSION
    - secure: "h6f32PIRZA/wjsDM/0/R/fFhOesZ/fQYPTynMinsU6V4Af6hKZx15dinXhIpMCnqUeYfAEvNXmVEz+3DAgZHwa4Kg/MbDzGOG/40QukBhdX4SEgywx+murt7HxA3BupAmvS7C/g/E/2lDIoK4K8718a1JNqNB+Hckgljg1J+plBz7Hc+DPpiY/CiYa2RPKfUqlGJIPGJIyV/alPwrHEFRFg7GVqlRbgMlNiLPsi0EsBEzeUWoizosn5UrAebKIGNdB/adDg7FvsjmHERuMEDABOTC2o0Y7VF2V3MTkSgxUSZRuGtHrrlwDM1s4Iba7r+Op6+QOiwDQjCHqACBiG4H/djOBMnvPuro76rmv1S1JG84IiDHToU+yB5MjHtMIatnHogKkZGSd28ptyzE+9vC8lafW+mpg8syLx8DxjH2yxDQXeFpKaVd22KBM8Wu5BU9hpwEYUhOx5dqQ3vLOsHmWTHgRB2w1gAfk15iIRismjSSeGnTrTXax1ZAYeQF5oLeFhslFi5EgKvexnJDLwnqbhOIp+KFoZGBWJUBcItUW7s4tHr9gFpiGZjaLqBL6M3DuCFJFZEPJp1+ARCkxiUBj9u9JRj44iYIgVe5jLUfkNE49Lb2TMRO5dxcglj753kNke6g4qYZ0+Yw1/mYSygifSMHg3vhjbFV3U2ATy+Ej8="
    - secure: "lkz0McNMJ+AtNnp+3uKzR+/lhJ8ggvHZ8SYbY+rYx8CcNCRmSqOhQPtI4gibBfJ2FWl6vqGWoMZFo5hk1nYAwccYQNM86wI7Hvwa7oiuNZC1ifGUHnchtrCOndSIPHGBG2UYLLYsuNjv2sYti5sRSS4ber8tFD6/SN33cVdOQCUDq5LagAfIpCukm++Kw6FSy4/BgUpsZvtQpgVbDIvexCvz/GQnBtLXR4k3j6iw3xv/VCibz7RaLrfygnx47hwHMv1VI/UjsOD5yHDaBBS0glDgxJh1BrEXNeu/LDHExJF26xwgOwVP4NzOnkDHim9yPT1koW0qoEuROlBdsHYW+Lir815VgOSJUuLAaKcrqkCFwoItdrX6HG7oCvmjNMjJBi8WOHh0uMJ3iZP5itwRng+J4gtivyHpnxv1ifNf1jPQWC2nLKuqqsi4nYEGbb3XO5AU3z1bWB4OQPdD7gQOPso+W5Z3MLCxhAI2vMj31ARi8Y+p/3v6Nm8P+M0agM35cCI1bPfbA/iSTmGpZiKIsg/DFSt5u2JCsMx5yY4u0tnNy03JG3qqJ9jNlEyvxWH1HUm1rmWx3cinixbeD1Z5lviXo4y12x2xF0As3qWZKeQhkCl2r70H4UIEH4k7qoIpWfoGAzmJ0yjS851ZlHCJlTqpmP4nKoVT/0IlcS0HcRE="
    - secure: "BHj6qiiFpFAWXBkn4LTBdvsqFAHZxQvQSerYtvBZz7RWpN/S22duttNXYGSpUaIuqAoFhJER1KaCetskj4EaEWWYHyC5BrSlRJSHg9ma/aJUWv8mObq2WmxOvgTFcEkNzy/YDM2RFtd6AfUaCaVs67di9AjiU+mEbTjigIaQXDUWCDs1sNSa5/gJcvT6J4dbgDmBRxsdjKdK3rj9VwdD3ObKwrM1wbqRz1C5CxB4uvuF0X09bh0GhU3QAraboKQlStMT1VGTbxI2iAHeLM7aAL2eXz5UvioezO+WrBBh0PB7TXzVfPwVl4B6msJVpc3iHDV/JJc5mpA40BZn8UW0/v3BLF4xWLBzNCykq8ZhqGHoP+5XNfnVaRZCmVI+t4jZ9bmBFyRPRWwl+ZJMXdN3MwCIPUt1WP1SmH96XTtR4AlfwPX2ip5Mce3fmeHS6hDO6z8FgmhX43E5Uw/DvWP35TjRbG6hIbG2HDsK3VfINtb4JADYQ8xbN/Ml3cConGwDEe8ObJ+iuwSCUbgI/ds2nzswLnjmKZVegJp8JDE5Q5yHOjJCB4dnAkK73AIEkTN1S/8usx1v4xLzlHwCN3gAJNAVCHsSat0rnwHG9Cnb/0RxC2vXgnxcpoksboTJ+1RyEHqtIPCWfgwV5PDf/qMSLXBaYRfjlvlkQY6eVN4fUxE="

  matrix:
    - VERSION=3.3.9
    - VERSION=3.5.2
    - VERSION=3.5.3
    - VERSION=3.6.0

before_install:
    - wget --no-check-certificate $(echo -n $BASEURL | sed -e 's#VERSION#'$VERSION'#g');
    - unzip -qq $(echo -n $FILE | sed -e 's#VERSION#'$VERSION'#');
    - export M2_HOME=$PWD/$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#');
    - export PATH=$M2_HOME/bin:$PATH;
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$JVM" == "latest" ]; then
         sudo apt-get update -qq;
         sudo /bin/echo -e oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections;
         sudo apt-get -o Dpkg::Options::="--force-confnew" install -y oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy;
         sudo update-java-alternatives -s java-9-oracle;
         sudo rm /etc/mavenrc;
         java -version;
     fi

install:
  # install without any testing to get dependencies in place
  - mvn install -U -Dmaven.test.skip=true -B -V -fae -T2

script:
  # execute unit and integration tests
  - mvn -e -fae -B -Dfailsafe.useFile=false -T2 clean test verify
  # check if all our javadoc is valid
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ] && [ "$VERSION" == "3.5.3" ]; then
         mvn javadoc:javadoc;
         mvn javadoc:test-javadoc;
    fi

after_success:
  # generate code coverage report, just for oraclejdk8 and latest maven
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
         mvn -B -e -fae -Ptravis-ci clean verify jacoco:report coveralls:report;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ] &&
       [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
         mvn deploy --settings .travis/settings.xml -DskipTests=true -B;
    else
        echo "Not deploying snapshot artifact";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ] &&
       [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
          mvn -e -fae -B site-deploy --settings .travis/settings.xml;
    else
          echo -n "not deploying maven site";
    fi

jdk:
  - oraclejdk8
  - openjdk8

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk9
      sudo: required
      dist: trusty
      group: edge
      env:
        - VERSION=3.5.3
        - JVM=latest

  allow_failures:

cache:
  directories:
  - $HOME/.m2
