init:
  - git config --global core.autocrlf true
  - git config --global core.safecrlf true

clone_folder: C:\projects\closure-compiler-maven-plugin

shallow_clone: false

version: "{build} ({branch})"

skip_tags: true

branches:
  except:
    - gh-pages

install:
  - cmd: echo %PATH%
  - cmd: java -version
  - cd C:\projects\closure-compiler-maven-plugin
  - mvn install -U -Dmaven.test.skip=true -B -V -fae -e -T2

build: off

test_script:
  - cd C:\projects\closure-compiler-maven-plugin
  - mvn -e -fae -B -Dfailsafe.useFile=false -T2 clean test verify

environment:

  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml
